filebeat.inputs:
  - type: filestream
    id: django-json
    enabled: true
    paths:
      - /app/logs/requests.jsonl
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true
          add_error_key: true
          ignore_decoding_error: true
    fields:
      app: gestao-financeira
      env: dev
    fields_under_root: true
    processors:
      - drop_event:
          when:
            not:
              has_fields: ["message"]
      - add_locale: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "django-logs-%{+yyyy.MM.dd}"

setup.template.name: "django-logs"
setup.template.pattern: "django-logs-*"
setup.ilm.enabled: false
