# Generated by Django 4.2.16 on 2025-09-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vencimento_nf', 'Vencimento NF'), ('vencimento_boleto', 'Vencimento Boleto'), ('orcamento', 'Orçamento'), ('caixa', 'Caixa')], max_length=20)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('push', 'Push')], default='email', max_length=10)),
                ('antecedencia_dias', models.IntegerField(default=3)),
                ('ativo', models.BooleanField(default=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='empresas.empresa')),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_id', models.IntegerField()),
                ('mes', models.CharField(max_length=7)),
                ('valor_planejado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='empresas.empresa')),
            ],
            options={
                'db_table': 'orcamentos_mensais',
                'unique_together': {('empresa', 'categoria_id', 'mes')},
            },
        ),
    ]
