# Generated by Django 4.2.16 on 2025-09-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('recorrencia', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('status', models.CharField(choices=[('previsto', 'Previsto'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='previsto', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='empresas.empresa')),
            ],
            options={
                'db_table': 'agendamentos',
                'ordering': ['-data_vencimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProjecaoSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('saldo_previsto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecoes_saldo', to='empresas.empresa')),
            ],
            options={
                'db_table': 'projecoes_saldo',
                'ordering': ['data'],
                'unique_together': {('empresa', 'data')},
            },
        ),
    ]
